version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: telegram-game-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
