async function fetchJSON(url, opts={}){ const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opts}); if(!r.ok) throw new Error(`HTTP ${r.status}`); return await r.json(); }
function toast(msg){ const t=document.getElementById('toast'); t.textContent=msg; t.classList.remove('hidden'); setTimeout(()=>t.classList.add('hidden'),2500); }

async function loadTokenMetrics(){ try{ const j=await fetchJSON('/api/token/metrics'); const m=j.metrics; document.getElementById('supply-cap').textContent=m.supplyCap.toLocaleString(); document.getElementById('minted').textContent=m.minted.toLocaleString(); document.getElementById('burned').textContent=m.burned.toLocaleString(); document.getElementById('circulation').textContent=m.circulation.toLocaleString(); }catch(e){ toast('Error cargando métricas de token'); console.error(e);} }
async function saveSupply(){ try{ const v=document.getElementById('input-supply').value; const j=await fetchJSON('/api/token/config',{method:'POST',body:JSON.stringify({supplyCap:v})}); document.getElementById('supply-cap').textContent=j.supplyCap.toLocaleString(); toast('Supply Cap actualizado'); }catch(e){ toast('Error guardando Supply Cap'); console.error(e);} }

async function loadXpConfig(){ try{ const j=await fetchJSON('/api/xp/config'); const t=j.thresholds||{}; const grid=document.getElementById('xp-grid'); grid.innerHTML=''; const levels=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]; for(const lv of levels){ const val=t[lv]??''; const el=document.createElement('div'); el.className='xp-item'; el.innerHTML=`<label>Nivel ${lv}</label><input type="number" min="0" id="xp-${lv}" value="${val}">`; grid.appendChild(el);} }catch(e){ toast('Error cargando configuración XP'); console.error(e);} }
async function saveXpConfig(){ try{ const levels=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]; const thresholds={}; for(const lv of levels){ const v=parseInt(document.getElementById(`xp-${lv}`).value,10); if(!Number.isNaN(v)) thresholds[lv]=v; } await fetchJSON('/api/xp/config',{method:'POST',body:JSON.stringify({thresholds})}); toast('Configuración XP guardada'); }catch(e){ toast('Error guardando configuración XP'); console.error(e);} }

window.addEventListener('DOMContentLoaded',()=>{ document.getElementById('refresh-token').addEventListener('click', loadTokenMetrics); document.getElementById('save-supply').addEventListener('click', saveSupply); document.getElementById('refresh-xp').addEventListener('click', loadXpConfig); document.getElementById('save-xp').addEventListener('click', saveXpConfig); loadTokenMetrics(); loadXpConfig(); });
